server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres # mudar user
    password: postgres # mudar senha
    initialization-mode: always # inicia data.sql
  jackson:
    date-format:dd/MM/yyyy